### PR TITLE
Remove downloads page?

### PR DESCRIPTION
**Pull request by terorie**
Requires #10

### CODE REVIEW

**Comment by terorie** [comment]
http://mine.terorie.com/ for test

**Comment by simon987** [comment]
Downloads page is temporarily empty but it is still in use for the csv exports

**Comment by terorie** [comment]
Understood. Judging by the code, currently only `static/out.csv.lzm4` is displayed for download. How about we change it to a listing of `static/downloads/*` instead?

**Comment by simon987** [comment]
Yes that feature would be helpful

**Comment by terorie** [comment]
Say no more, #13

**Pull request closed without merging**
